=== alekseykondus/oop-2021-2022-semester-1/Lab2/XML_project/resourses/Medicine.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://www.example.org/Medicine"
           xmlns:tns="http://www.example.org/Medicine"
           elementFormDefault="qualified">
    <xs:element name="Medicines">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="medicine" type="tns:Medicine" minOccurs="1" maxOccurs="100"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:complexType name="Medicine">
        <xs:sequence>
            <xs:element name="id">
                <xs:simpleType>
                    <xs:restriction base="xs:ID">
                        <xs:pattern value="[0-9][0-9][0-9]"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="Name" type="xs:string"/>
            <xs:element name="Pharm" type="xs:string"/>
            <xs:element name="Group">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:enumeration value="Antibiotics"/>
                        <xs:enumeration value="Sedative"/>
                        <xs:enumeration value="Vitamins"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="Analogs" type="xs:string" minOccurs="1" maxOccurs="100"/>
            <xs:element name="Versions">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:enumeration value="Pills"/>
                        <xs:enumeration value="Capsules"/>
                        <xs:enumeration value="Powder"/>
                        <xs:enumeration value="Drops"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="Certificate" type = "tns:certificate"/>
            <xs:element name="Package" type = "tns:package"/>
            <xs:element name="Dosage" type = "tns:dosage"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="certificate">
        <xs:sequence>
            <xs:element name="Number" type="xs:int"/>
            <xs:element name="ExpireDate" type="xs:string"/>
            <xs:element name="RegisteringOrganization " type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name = "package">
        <xs:sequence>
            <xs:element name="TypeOfPackaging">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:enumeration value="Paper"/>
                        <xs:enumeration value="Polyethylene"/>
                        <xs:enumeration value="Glass"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="AmountInPackage" type="xs:int"/>
            <xs:element name="Price" type="xs:double"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name = "dosage">
        <xs:sequence>
            <xs:element name="DrugDosage" type="xs:string"/>
            <xs:element name="FrequencyOfAdmission " type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== alekseykondus/oop-2021-2022-semester-1/Lab2/XML_project/resourses/medicines.xml
<?xml version="1.0" encoding="UTF-8"?>
<Medicines xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="Medicine.xsd">
    <Medicine id="1" Name="Preparate1">
        <id>1</id>
        <Name>Preparate1</Name>
        <Pharm>Pharm1</Pharm>
        <Group>Sedative</Group>
        <Analogs>Analogs1</Analogs>
        <Analogs>Analogs2</Analogs>
        <Versions>Versions1</Versions>
        <Certificate>
            <Number>1234521</Number>
            <ExpireDate>20.11.22</ExpireDate>
            <RegisteringOrganization>RegisteringOrganization1</RegisteringOrganization>
        </Certificate>
        <Package>
            <TypeOfPackaging>Glass</TypeOfPackaging>
            <AmountInPackage>158</AmountInPackage>
            <Price>12.25</Price>
        </Package>
        <Dosage>
            <DrugDosage>DrugDosage1</DrugDosage>
            <FrequencyOfAdmission>FrequencyOfAdmission1</FrequencyOfAdmission>
        </Dosage>
    </Medicine>

    <Medicine id="2" Name="Preparate_2">
        <id>2</id>
        <Name>Preparate_2</Name>
        <Pharm>Pharm_1</Pharm>
        <Group>Sedative</Group>
        <Analogs>Analogs_2_1</Analogs>
        <Analogs>Analogs_2_2</Analogs>
        <Versions>Versions_2</Versions>
        <Certificate>
            <Number>42524</Number>
            <ExpireDate>12.11.23</ExpireDate>
            <RegisteringOrganization>RegisteringOrganization_2</RegisteringOrganization>
        </Certificate>
        <Package>
            <TypeOfPackaging>Glass</TypeOfPackaging>
            <AmountInPackage>158</AmountInPackage>
            <Price>12.25</Price>
        </Package>
        <Dosage>
            <DrugDosage>DrugDosage1</DrugDosage>
            <FrequencyOfAdmission>FrequencyOfAdmission1</FrequencyOfAdmission>
        </Dosage>
    </Medicine>
</Medicines>
